// -------------------------------------------------------------------------------------------------
// <copyright file="MessageSort.cs" company="Starion Group S.A.">
//
//   Copyright (C) 2019-2025 Starion Group S.A.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace uml4net.Interactions
{
    /// <summary>
    /// This is an enumerated type that identifies the type of communication action that was used to
    /// generate the Message.
    /// </summary>
    public enum MessageSort
    {
        /// <summary>
        /// The message was generated by a synchronous call to an operation.
        /// </summary>
        SynchCall,

        /// <summary>
        /// The message was generated by an asynchronous call to an operation; i.e., a CallAction with
        /// isSynchronous = false.
        /// </summary>
        AsynchCall,

        /// <summary>
        /// The message was generated by an asynchronous send action.
        /// </summary>
        AsynchSignal,

        /// <summary>
        /// The message designating the creation of another lifeline object.
        /// </summary>
        CreateMessage,

        /// <summary>
        /// The message designating the termination of another lifeline.
        /// </summary>
        DeleteMessage,

        /// <summary>
        /// The message is a reply message to an operation call.
        /// </summary>
        Reply
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
