// -------------------------------------------------------------------------------------------------
// <copyright file="MessageSort.cs" company="Starion Group S.A.">
//
//   Copyright (C) 2019-2026 Starion Group S.A.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace uml4net.Interactions
{
    using System;

    /// <summary>
    /// This is an enumerated type that identifies the type of communication action that was used to
    /// generate the Message.
    /// </summary>
    public enum MessageSort
    {
        /// <summary>
        /// The message was generated by a synchronous call to an operation.
        /// </summary>
        SynchCall,

        /// <summary>
        /// The message was generated by an asynchronous call to an operation; i.e., a CallAction with
        /// isSynchronous = false.
        /// </summary>
        AsynchCall,

        /// <summary>
        /// The message was generated by an asynchronous send action.
        /// </summary>
        AsynchSignal,

        /// <summary>
        /// The message designating the creation of another lifeline object.
        /// </summary>
        CreateMessage,

        /// <summary>
        /// The message designating the termination of another lifeline.
        /// </summary>
        DeleteMessage,

        /// <summary>
        /// The message is a reply message to an operation call.
        /// </summary>
        Reply
    }

    /// <summary>
    /// Extension methods for the <see cref="MessageSort"/> enumeration
    /// </summary>
    public static class MessageSortExtensions
    {
        /// <summary>
        /// Queries the name of the enumeration literal as defined in the UML metamodel, which is the value that
        /// represents the <paramref name="value"/> in an XMI document (XMI 2.5.1 clause 9.5.2, rule 2i)
        /// </summary>
        /// <param name="value">
        /// The <see cref="MessageSort"/> value
        /// </param>
        /// <returns>
        /// the name of the enumeration literal
        /// </returns>
        public static string QueryXmiLiteral(this MessageSort value)
        {
            return value switch
            {
                MessageSort.SynchCall => "synchCall",
                MessageSort.AsynchCall => "asynchCall",
                MessageSort.AsynchSignal => "asynchSignal",
                MessageSort.CreateMessage => "createMessage",
                MessageSort.DeleteMessage => "deleteMessage",
                MessageSort.Reply => "reply",
                _ => throw new ArgumentOutOfRangeException(nameof(value), value, $"{value} is not a literal of MessageSort")
            };
        }

        /// <summary>
        /// Tries to map the name of an enumeration literal as it appears in an XMI document (XMI 2.5.1 clause 9.5.2,
        /// rule 2i) to the <see cref="MessageSort"/> value; the name must match the literal of the UML metamodel
        /// exactly, numeric values and other spellings are not literals
        /// </summary>
        /// <param name="literal">
        /// The name of the enumeration literal
        /// </param>
        /// <param name="value">
        /// The <see cref="MessageSort"/> value, the default value when the literal is not known
        /// </param>
        /// <returns>
        /// true when the literal is a literal of <see cref="MessageSort"/>, false otherwise
        /// </returns>
        public static bool TryParseXmiLiteral(string literal, out MessageSort value)
        {
            switch (literal)
            {
                case "synchCall":
                    value = MessageSort.SynchCall;
                    return true;
                case "asynchCall":
                    value = MessageSort.AsynchCall;
                    return true;
                case "asynchSignal":
                    value = MessageSort.AsynchSignal;
                    return true;
                case "createMessage":
                    value = MessageSort.CreateMessage;
                    return true;
                case "deleteMessage":
                    value = MessageSort.DeleteMessage;
                    return true;
                case "reply":
                    value = MessageSort.Reply;
                    return true;
                default:
                    value = default;
                    return false;
            }
        }
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
