<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Description>Nunit test suite for the uml4net.Tools library</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Moq" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\uml4net.Tools\uml4net.Tools.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\resources\UML\forge.xmi">
          <Link>TestData\forge.xmi</Link>
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="..\resources\UML\PrimitiveTypes.xmi" Link="TestData\PrimitiveTypes.xmi">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="..\resources\UML\UML.xmi" Link="TestData\UML.xmi">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <None Include="..\resources\SySML2\SysML.uml" Link="TestData\SysML.uml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
