// -------------------------------------------------------------------------------------------------
//  <copyright file="ExtenderReaderRegistry .cs" company="Starion Group S.A.">
// 
//    Copyright (C) 2019-2026 Starion Group S.A.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
// 
//  </copyright>
//  ------------------------------------------------------------------------------------------------

namespace uml4net.xmi.Extender
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using Autofac.Features.Metadata;

    using uml4net.xmi.Readers;

    /// <summary>
    /// Provides a dynamic resolution mechanism to locate a concrete <see cref="IExtenderReader"/>
    /// implementation based on the <c>extender</c> and <c>extenderID</c> attributes
    /// of an <c>xmi:Extension</c> element.
    /// </summary>
    /// <remarks>
    /// This class is typically used at runtime to delegate the parsing of tool-specific
    /// XMI extension content (e.g., generated by Enterprise Architect, MagicDraw, Papyrus).
    /// </remarks>
    public class ExtenderReaderRegistry : IExtenderReaderRegistry
    {
        /// <summary>
        /// Gets the injected collection of available <see cref="IExtenderReader"/>
        /// </summary>
        private readonly IEnumerable<Meta<IExtenderReader>> extenderReaders;

        /// <summary>
        ///Gets the injected collection of available <see cref="IExtensionContentReaderFacade" />
        /// </summary>
        private readonly IEnumerable<Meta<IExtensionContentReaderFacade>> extenderFacades;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExtenderReaderRegistry"/> class.
        /// </summary>
        /// <param name="extenderReaders">
        /// The collection of available <see cref="IExtenderReader"/> implementations, 
        /// each wrapped in a <see cref="Autofac.Features.Metadata.Meta{T}"/> object that 
        /// exposes registration metadata such as <c>Extender</c> and <c>ExtenderId</c>.
        /// <para>
        /// This collection is automatically provided by the dependency injection container 
        /// and typically populated through the <c>WithExtender&lt;T&gt;</c> or 
        /// <c>WithAllExtendersFrom(...)</c> registration helpers.
        /// </para>
        /// </param>
        /// <param name="extenderFacades">
        /// The collection of available <see cref="IExtensionContentReaderFacade"/> implementations, 
        /// each wrapped in a <see cref="Autofac.Features.Metadata.Meta{T}"/> object that 
        /// exposes registration metadata such as <c>Extender</c> and <c>ExtenderId</c>.
        /// <para>
        /// This collection is automatically provided by the dependency injection container 
        /// and typically populated through the <c>WithExtender&lt;T&gt;</c> or 
        /// <c>WithAllExtendersFrom(...)</c> registration helpers.</para></param>
        /// <remarks>
        /// The registry uses the metadata associated with each <see cref="IExtenderReader"/>
        /// to dynamically resolve the correct reader implementation based on the
        /// <c>extender</c> and <c>extenderID</c> attributes of an <c>xmi:Extension</c> element.
        /// </remarks>
        public ExtenderReaderRegistry(IEnumerable<Meta<IExtenderReader>> extenderReaders, IEnumerable<Meta<IExtensionContentReaderFacade>> extenderFacades)
        {
            this.extenderReaders = extenderReaders;
            this.extenderFacades = extenderFacades;
        }

        /// <summary>
        /// Resolves the <see cref="IExtenderReader"/> responsible for handling the given extender and optional extenderId.
        /// </summary>
        /// <param name="extender">
        /// The value of the <c>extender</c> attribute from the <c>xmi:Extension</c> element.
        /// </param>
        /// <param name="extenderId">
        /// The optional value of the <c>extenderID</c> attribute from the <c>xmi:Extension</c> element.
        /// </param>
        /// <returns>
        /// A matching <see cref="IExtenderReader"/> instance if registered; otherwise, <c>null</c>.
        /// </returns>
        public IExtenderReader Resolve(string extender, string extenderId = null)
        {
            return ResolveCollection(this.extenderReaders, extender, extenderId);
        }

        /// <summary>
        /// Resolves the <see cref="IExtensionContentReaderFacade"/> responsible for handling the given extender and optional extenderId.
        /// </summary>
        /// <param name="extender">
        /// The value of the <c>extender</c> attribute from the <c>xmi:Extension</c> element.
        /// </param>
        /// <param name="extenderId">
        /// The optional value of the <c>extenderID</c> attribute from the <c>xmi:Extension</c> element.
        /// </param>
        /// <returns>
        /// A matching <see cref="IExtensionContentReaderFacade"/> instance if registered; otherwise, <c>null</c>.
        /// </returns>
        public IExtensionContentReaderFacade ResolveFacade(string extender, string extenderId = null)
        {
            return ResolveCollection(this.extenderFacades, extender, extenderId);
        }

        /// <summary>
        /// Resolves the <typeparamref name="T"/> responsible for handling the given extender and optional extenderId.
        /// </summary>
        /// <param name="collection">The collection of registered <typeparamref name="T"/></param>
        /// <param name="extender">
        /// The value of the <c>extender</c> attribute from the <c>xmi:Extension</c> element.
        /// </param>
        /// <param name="extenderId">
        /// The optional value of the <c>extenderID</c> attribute from the <c>xmi:Extension</c> element.
        /// </param>
        /// <returns>
        /// A matching <typeparamref name="T"/> instance if registered; otherwise, <c>null</c>.
        /// </returns>
        /// <typeparam name="T">Any class</typeparam>
        private static T ResolveCollection<T>(IEnumerable<Meta<T>> collection, string extender, string extenderId = null) where T: class
        {
            return collection.FirstOrDefault(meta =>
            {
                var metaExtender = meta.Metadata["Extender"] as string;
                var metaExtenderId = meta.Metadata["ExtenderId"] as string;

                if (!string.Equals(extender, metaExtender, StringComparison.OrdinalIgnoreCase))
                {
                    return false;
                }

                return string.IsNullOrEmpty(metaExtenderId) || string.Equals(extenderId, metaExtenderId, StringComparison.OrdinalIgnoreCase);
            })?.Value;
        }
    }
}
