// -------------------------------------------------------------------------------------------------
//  <copyright file="ExtenderReaderRegistry .cs" company="Starion Group S.A.">
// 
//    Copyright 2019-2025 Starion Group S.A.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
// 
//  </copyright>
//  ------------------------------------------------------------------------------------------------

namespace uml4net.xmi.Extender
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using Autofac.Features.Metadata;

    /// <summary>
    /// Provides a dynamic resolution mechanism to locate a concrete <see cref="IExtenderReader"/>
    /// implementation based on the <c>extender</c> and <c>extenderID</c> attributes
    /// of an <c>xmi:Extension</c> element.
    /// </summary>
    /// <remarks>
    /// This class is typically used at runtime to delegate the parsing of tool-specific
    /// XMI extension content (e.g., generated by Enterprise Architect, MagicDraw, Papyrus).
    /// </remarks>
    public class ExtenderReaderRegistry : IExtenderReaderRegistry
    {
        /// <summary>
        /// Gets the injected collection of available <see cref="IExtenderReader"/>
        /// </summary>
        private readonly IEnumerable<Meta<IExtenderReader>> extenderReaders;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExtenderReaderRegistry"/> class.
        /// </summary>
        /// <param name="extenderReaders">
        /// The collection of available <see cref="IExtenderReader"/> implementations, 
        /// each wrapped in a <see cref="Autofac.Features.Metadata.Meta{T}"/> object that 
        /// exposes registration metadata such as <c>Extender</c> and <c>ExtenderId</c>.
        /// <para>
        /// This collection is automatically provided by the dependency injection container 
        /// and typically populated through the <c>WithExtender&lt;T&gt;</c> or 
        /// <c>WithAllExtendersFrom(...)</c> registration helpers.
        /// </para>
        /// </param>
        /// <remarks>
        /// The registry uses the metadata associated with each <see cref="IExtenderReader"/>
        /// to dynamically resolve the correct reader implementation based on the
        /// <c>extender</c> and <c>extenderID</c> attributes of an <c>xmi:Extension</c> element.
        /// </remarks>
        public ExtenderReaderRegistry(IEnumerable<Meta<IExtenderReader>> extenderReaders)
        {
            this.extenderReaders = extenderReaders;
        }

        /// <summary>
        /// Resolves the <see cref="IExtenderReader"/> responsible for handling the given extender and optional extenderId.
        /// </summary>
        /// <param name="extender">
        /// The value of the <c>extender</c> attribute from the <c>xmi:Extension</c> element.
        /// </param>
        /// <param name="extenderId">
        /// The optional value of the <c>extenderID</c> attribute from the <c>xmi:Extension</c> element.
        /// </param>
        /// <returns>
        /// A matching <see cref="IExtenderReader"/> instance if registered; otherwise, <c>null</c>.
        /// </returns>
        public IExtenderReader Resolve(string extender, string extenderId = null)
        {
            return this.extenderReaders.FirstOrDefault(meta =>
            {
                var metaExtender = meta.Metadata["Extender"] as string;
                var metaExtenderId = meta.Metadata["ExtenderId"] as string;

                if (!string.Equals(extender, metaExtender, StringComparison.OrdinalIgnoreCase))
                {
                    return false;
                }

                if (!string.IsNullOrEmpty(metaExtenderId))
                {
                    return string.Equals(extenderId, metaExtenderId, StringComparison.OrdinalIgnoreCase);
                }

                return true;

            })?.Value;
        }
    }
}
