// -------------------------------------------------------------------------------------------------
//  <copyright file="IExtenderReaderRegistry.cs" company="Starion Group S.A.">
// 
//    Copyright 2019-2025 Starion Group S.A.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
// 
//  </copyright>
//  ------------------------------------------------------------------------------------------------

namespace uml4net.xmi.Extender
{
    /// <summary>
    /// Provides a dynamic resolution mechanism to locate a concrete <see cref="IExtenderReader"/>
    /// implementation based on the <c>extender</c> and <c>extenderID</c> attributes
    /// of an <c>xmi:Extension</c> element.
    /// </summary>
    /// <remarks>
    /// This interface is typically used at runtime to delegate the parsing of tool-specific
    /// XMI extension content (e.g., generated by Enterprise Architect, MagicDraw, Papyrus).
    /// </remarks>
    public interface IExtenderReaderRegistry
    {
        /// <summary>
        /// Resolves the <see cref="IExtenderReader"/> responsible for handling the given extender and optional extenderId.
        /// </summary>
        /// <param name="extender">
        /// The value of the <c>extender</c> attribute from the <c>xmi:Extension</c> element.
        /// </param>
        /// <param name="extenderId">
        /// The optional value of the <c>extenderID</c> attribute from the <c>xmi:Extension</c> element.
        /// </param>
        /// <returns>
        /// A matching <see cref="IExtenderReader"/> instance if registered; otherwise, <c>null</c>.
        /// </returns>
        IExtenderReader Resolve(string extender, string extenderId = null);
    }
}
