<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Version>8.2.1</Version>
        <LangVersion>12.0</LangVersion>
        <PackageId>uml4net.Extensions</PackageId>
        <AssemblyTitle>uml4net.Extensions</AssemblyTitle>
        <Title>uml4net.Extensions</Title>
        <Description>Extension methods for the .NET implementation of the OMG UML v2.5.1 specification.</Description>
        <PackageTags>UML modeltopia</PackageTags>
        <PackageReleaseNotes>
            [Bump] to uml4net 4.2.1
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\uml4net\uml4net.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="HtmlAgilityPack" />
    </ItemGroup>
</Project>
