<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Version>8.6.0</Version>
        <LangVersion>12.0</LangVersion>
        <PackageId>uml4net.xmi.Extensions.EnterpriseArchitect</PackageId>
        <AssemblyTitle>uml4net.xmi.Extensions.EnterpriseArchitect</AssemblyTitle>
        <Title>uml4net.xmi.Extensions.EnterpriseArchitect</Title>
        <Description>A specific XMI Reader extension to support Enterprise Architect XMI reading</Description>
        <PackageTags>UML XMI modeltopia</PackageTags>
        <PackageReleaseNotes>
            [Add] Constraint extension element, the ConstraintStatus enumeration and the Constraints property on Element, Attribute and Connector; fixes #217
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\uml4net.xmi\uml4net.xmi.csproj" />
    </ItemGroup>
</Project>
