// -------------------------------------------------------------------------------------------------
// <copyright file="MessageSort.cs" company="RHEA System S.A.">
//   Copyright (c) 2018-2019 RHEA System S.A.
//
//   This file is part of uml-sharp
//
//   uml-sharp is free software: you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//   
//   uml-sharp is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with uml-sharp. If not, see<http://www.gnu.org/licenses/>.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace Uml.Interactions
{
    /// <summary>
    /// This is an enumerated type that identifies the type of communication action that was used to generate the Message.
    /// </summary>
    public enum MessageSort
    {
        /// <summary>
        /// The message was generated by a synchronous call to an operation.
        /// </summary>
        SynchCall,

        /// <summary>
        /// The message was generated by an asynchronous call to an operation; i.e., a CallAction with isSynchronous = false.
        /// </summary>
        AsynchCall,

        /// <summary>
        /// The message was generated by an asynchronous send action.
        /// </summary>
        AsynchSignal,

        /// <summary>
        /// The message designating the creation of another lifeline object.
        /// </summary>
        CreateMessage,

        /// <summary>
        /// The message designating the termination of another lifeline.
        /// </summary>
        DeleteMessage,

        /// <summary>
        /// The message is a reply message to an operation call.
        /// </summary>
        Reply
    }
}