<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Version>8.4.0</Version>
        <LangVersion>12.0</LangVersion>
        <PackageId>uml4net.xmi</PackageId>
        <AssemblyTitle>uml4net.xmi</AssemblyTitle>
        <Title>uml4net.xmi</Title>
        <Description>An XMI implementation for the .NET implementation of the OMG UML v2.5.1 specification.</Description>
        <PackageTags>UML XMI modeltopia</PackageTags>
        <PackageReleaseNotes>
            [Feature] write the xmi:Extension content to an XMI document; fixes #200
            [Fix] preserve unresolved external references as raw XMI; fixes #204
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Resources\UML.xmi" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="..\resources\UML\PrimitiveTypes.xmi" Link="Resources\PrimitiveTypes.xmi" />
        <EmbeddedResource Include="..\resources\UML\StandardProfile.xmi" Link="Resources\StandardProfile.xmi" />
        <EmbeddedResource Include="Resources\UML.xmi" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\uml4net.Extensions\uml4net.Extensions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" />
    </ItemGroup>
</Project>
